steps:

- id: 'Rodando docker-compose'
  name: 'gcr.io/$PROJECT_ID/docker-compose:1.24.0'
  args: ['-f', 'docker-compose-cloudbuild.yaml', 'up', '-d']

- id: 'Verificando se os containers etão rodando docker ps'
  name: 'gcr.io/cloud_builders/docker'
  args: ['ps']

- id: 'Rodando composer install'
  name: 'gcr.io/cloud_builders/docker'
  args: ['exec', '-t', 'app', 'composer', 'install']

- id: 'Copiando .env'
  name: 'gcr.io/cloud_builders/docker'
  args: ['exec', '-t', 'app', 'cp', '.env.example', '.env']

- id: 'Rodando key:generate'
  name: 'gcr.io/cloud_builders/docker'
  args: ['exec', '-t', 'app', 'cp', '/var/www/artisan', 'key:generate']

- id: 'Rodando migrations'
  name: 'gcr.io/cloud_builders/docker'
  args: ['exec', '-t', 'app', 'cp', '/var/www/artisan', 'migrate']

- id: 'Rodando Testes phpunit'
  name: 'gcr.io/cloud_builders/docker'
  args: ['exec', '-t', 'app', 'cp', '/var/www/vendor/bin/phpunit', 'migrate', '-c', '/var/www/phpunit.xml']